// Static-import registry for the parsed volume data.
//
// Static imports rather than fs reads, so the whole set is validated at build
// time and works identically in a server component and a client component.
// An unknown slug is a 404 rather than a runtime surprise.
//
// Extraction 6.9 warns this does not scale past a dozen or so entries and
// should be generated by then. At eight it is still cheaper to read than a glob.

import roster from '@/patch-notes/roster.json';
import vol1 from '@/patch-notes/volumes/vol1.json';
import vol2 from '@/patch-notes/volumes/vol2.json';
import vol3 from '@/patch-notes/volumes/vol3.json';
import vol4 from '@/patch-notes/volumes/vol4.json';
import u1 from '@/patch-notes/volumes/u1.json';
import u2 from '@/patch-notes/volumes/u2.json';
import u3 from '@/patch-notes/volumes/u3.json';
import u4 from '@/patch-notes/volumes/u4.json';

const REGISTRY = { vol1, vol2, vol3, vol4, u1, u2, u3, u4 };

export { roster };

/**
 * Reading order WITHIN an arc, which is the only order that means anything.
 *
 * This was one flat list while there was one arc, and every consumer read it as "the
 * volumes". With two arcs a flat list quietly says that Volume 4 of The Patch is followed
 * by Volume 1 of The Understudies, which is how "next volume" at the end of an arc would
 * have carried a reader straight into a different story.
 *
 * The arc id is carried in the JSON by parse-specs rather than restated here, so adding an
 * arc is a spec change plus one import above.
 */
const ARC_ORDER = ['patch-notes', 'understudies'];

export const VOLUME_SLUGS = Object.keys(REGISTRY);

export const slugsForArc = (arcId) =>
  VOLUME_SLUGS.filter((s) => REGISTRY[s].arc === arcId);

export const ARCS_WITH_VOLUMES = ARC_ORDER.filter((a) => slugsForArc(a).length > 0);

/** Where a volume is read. Derived from its arc, never hardcoded at a call site. */
export const readHref = (slug) => `/${REGISTRY[slug]?.arc ?? 'patch-notes'}/${slug}/read`;

/**
 * One volume, shaped for the reader.
 *
 * Returns null for an unknown slug so the route decides what a 404 is.
 */
export function loadVolume(slug) {
  const v = REGISTRY[slug];
  if (!v) return null;

  const textSpreads = v.spreads.filter((s) => s.kind === 'spread');

  return {
    slug,
    ...v,
    // Derived, never duplicated in the data. Extraction 6.10: Unbroke carried
    // spreadCount in its manifest AND computed it in the loader, with nothing
    // checking the two agreed.
    spreadCount: textSpreads.length,
    imageCount: v.spreads.length,
    words: textSpreads.reduce((a, s) => a + s.words, 0),
    // The jump list, built from the ### section headings inside the prose. The
    // build brief asks for exactly this rather than a separate chapter list.
    sections: textSpreads.flatMap((s) =>
      s.blocks
        .filter((b) => b.t === 'h')
        .map((b) => ({ title: b.v, spread: s.n })),
    ),
  };
}

export function allVolumes() {
  return VOLUME_SLUGS.map(loadVolume);
}

/**
 * Where a reader goes when they finish a volume.
 *
 * Returns the next volume in the SAME arc, or null at the end of it, which is the caller's
 * cue to offer the shelf instead. Scoped to the arc deliberately: running off the end of
 * The Patch into The Understudies would hand a reader the next arc's Volume 1 with no
 * indication they had left the story they were reading.
 *
 * Shaped on the server and handed to the reader as a prop rather than derived inside it:
 * FlipBook has no business knowing the site's route structure, and the title has to come
 * from the volume data either way.
 */
export function nextVolume(slug) {
  const arc = REGISTRY[slug]?.arc;
  const order = slugsForArc(arc);
  const i = order.indexOf(slug);
  if (i < 0 || i === order.length - 1) return null;

  const next = loadVolume(order[i + 1]);
  if (!next) return null;

  return {
    slug: next.slug,
    href: readHref(next.slug),
    // "Part Four: The Press Conference" is how the volume names itself; the
    // reader wants the part and the title separately so it can set them at
    // different weights.
    part: next.chapter.match(/^(Part\s+\w+)/i)?.[1] ?? `Volume ${i + 2}`,
    title: next.chapter.replace(/^Part\s+\w+:\s*/i, ''),
  };
}
