// Static-import registry for the parsed volume data.
//
// Static imports rather than fs reads, so the whole set is validated at build
// time and works identically in a server component and a client component.
// Four volumes is small enough that a hand-written registry beats a dynamic
// glob: an unknown slug is a 404 rather than a runtime surprise.
//
// Extraction 6.9 warns this does not scale past a dozen or so entries and
// should be generated by then. At four, generating it would be more machinery
// than it saves.

import roster from '@/patch-notes/roster.json';
import vol1 from '@/patch-notes/volumes/vol1.json';
import vol2 from '@/patch-notes/volumes/vol2.json';
import vol3 from '@/patch-notes/volumes/vol3.json';
import vol4 from '@/patch-notes/volumes/vol4.json';

const REGISTRY = { vol1, vol2, vol3, vol4 };

export { roster };

export const VOLUME_SLUGS = Object.keys(REGISTRY);

/**
 * One volume, shaped for the reader.
 *
 * Returns null for an unknown slug so the route decides what a 404 is.
 */
export function loadVolume(slug) {
  const v = REGISTRY[slug];
  if (!v) return null;

  const textSpreads = v.spreads.filter((s) => s.kind === 'spread');

  return {
    slug,
    ...v,
    // Derived, never duplicated in the data. Extraction 6.10: Unbroke carried
    // spreadCount in its manifest AND computed it in the loader, with nothing
    // checking the two agreed.
    spreadCount: textSpreads.length,
    imageCount: v.spreads.length,
    words: textSpreads.reduce((a, s) => a + s.words, 0),
    // The jump list, built from the ### section headings inside the prose. The
    // build brief asks for exactly this rather than a separate chapter list.
    sections: textSpreads.flatMap((s) =>
      s.blocks
        .filter((b) => b.t === 'h')
        .map((b) => ({ title: b.v, spread: s.n })),
    ),
  };
}

export function allVolumes() {
  return VOLUME_SLUGS.map(loadVolume);
}
