// Static-import registry for the parsed volume data.
//
// Static imports rather than fs reads, so the whole set is validated at build
// time and works identically in a server component and a client component.
// Four volumes is small enough that a hand-written registry beats a dynamic
// glob: an unknown slug is a 404 rather than a runtime surprise.
//
// Extraction 6.9 warns this does not scale past a dozen or so entries and
// should be generated by then. At four, generating it would be more machinery
// than it saves.

import roster from '@/patch-notes/roster.json';
import vol1 from '@/patch-notes/volumes/vol1.json';
import vol2 from '@/patch-notes/volumes/vol2.json';
import vol3 from '@/patch-notes/volumes/vol3.json';
import vol4 from '@/patch-notes/volumes/vol4.json';

const REGISTRY = { vol1, vol2, vol3, vol4 };

export { roster };

export const VOLUME_SLUGS = Object.keys(REGISTRY);

/**
 * One volume, shaped for the reader.
 *
 * Returns null for an unknown slug so the route decides what a 404 is.
 */
export function loadVolume(slug) {
  const v = REGISTRY[slug];
  if (!v) return null;

  const textSpreads = v.spreads.filter((s) => s.kind === 'spread');

  return {
    slug,
    ...v,
    // Derived, never duplicated in the data. Extraction 6.10: Unbroke carried
    // spreadCount in its manifest AND computed it in the loader, with nothing
    // checking the two agreed.
    spreadCount: textSpreads.length,
    imageCount: v.spreads.length,
    words: textSpreads.reduce((a, s) => a + s.words, 0),
    // The jump list, built from the ### section headings inside the prose. The
    // build brief asks for exactly this rather than a separate chapter list.
    sections: textSpreads.flatMap((s) =>
      s.blocks
        .filter((b) => b.t === 'h')
        .map((b) => ({ title: b.v, spread: s.n })),
    ),
  };
}

export function allVolumes() {
  return VOLUME_SLUGS.map(loadVolume);
}

/**
 * Where a reader goes when they finish a volume.
 *
 * Returns the next volume in reading order, or null at the end of the arc, which
 * is the caller's cue to offer the shelf instead. Order comes from VOLUME_SLUGS,
 * the same list that generates the routes, so a fifth volume needs no edit here.
 *
 * Shaped on the server and handed to the reader as a prop rather than derived
 * inside it: FlipBook has no business knowing the site's route structure, and the
 * title has to come from the volume data either way.
 */
export function nextVolume(slug) {
  const i = VOLUME_SLUGS.indexOf(slug);
  if (i < 0 || i === VOLUME_SLUGS.length - 1) return null;

  const next = loadVolume(VOLUME_SLUGS[i + 1]);
  if (!next) return null;

  return {
    slug: next.slug,
    href: `/patch-notes/${next.slug}/read`,
    // "Part Four: The Press Conference" is how the volume names itself; the
    // reader wants the part and the title separately so it can set them at
    // different weights.
    part: next.chapter.match(/^(Part\s+\w+)/i)?.[1] ?? `Volume ${i + 2}`,
    title: next.chapter.replace(/^Part\s+\w+:\s*/i, ''),
  };
}
